/**
 * Regenerates packages/core/src/highlights/font-metrics.ts from the fonts shipped for highlight text.
 * Run after adding or replacing a font in apps/desktop/resources/fonts:
 *
 *   node scripts/font-metrics.ts
 */
import { readFile, writeFile } from "node:fs/promises"
import { HIGHLIGHT_FONTS } from "../packages/core/src/highlights/styles.ts"
import { METRIC_CHARS, readFontMetrics, type FontMetrics } from "../packages/core/src/highlights/ttf.ts"

const fonts = new URL("../apps/desktop/resources/fonts/", import.meta.url)
const target = new URL("../packages/core/src/highlights/font-metrics.ts", import.meta.url)

const metrics: Record<string, FontMetrics> = {}
for (const [id, file] of Object.entries(HIGHLIGHT_FONTS)) {
  metrics[id] = readFontMetrics(await readFile(new URL(file, fonts)), METRIC_CHARS)
}

await writeFile(
  target,
  `// Generated by scripts/font-metrics.ts from apps/desktop/resources/fonts. Do not edit.
import type { HighlightFontId } from "./styles.ts"
import type { FontMetrics } from "./ttf.ts"

export const FONT_METRICS: Record<HighlightFontId, FontMetrics> = ${JSON.stringify(metrics, null, 2)}
`,
)
console.log(`wrote ${Object.keys(metrics).length} fonts to ${target.pathname}`)
