import { chromium } from 'playwright';
import { writeFileSync } from 'node:fs';
const OUT = process.argv[2] + '/shots', man = {};
const b = await chromium.launch();
let p;
const open = async (q) => { if (p) await p.close(); p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1.5, colorScheme: 'light' }); p.on('pageerror', e => console.log('ERR', e.message)); await p.goto('http://localhost:5179/' + q); await p.waitForTimeout(1500); };
const box = async (loc) => { const r = await loc.first().boundingBox({ timeout: 3000 }).catch(() => null); return r ? [Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height)] : null; };
const shot = async (id, targets = {}, wait = 500) => {
  await p.waitForTimeout(wait);
  const boxes = {}; for (const [k, loc] of Object.entries(targets)) boxes[k] = await box(loc);
  await p.screenshot({ path: OUT + '/' + id + '.jpg', type: 'jpeg', quality: 88 });
  man[id] = { file: 'shots/' + id + '.jpg', boxes }; console.log(id, JSON.stringify(boxes));
};
const seq = async (id, count, every, targets = {}) => { for (let i = 0; i < count; i++) { await shot(id + '_' + i, i === 0 ? targets : {}, i ? every : 50); } man[id] = { seq: count, every }; };
const btn = (name) => p.getByRole('button', { name });
const tab = (name) => p.getByRole('tab', { name });

/* ---- first launch ---- */
await open('?fresh');
await shot('act', { input: p.locator('input').first(), submit: btn('เปิดใช้งาน') });
await p.locator('input').first().pressSequentially('PD2-7K3QM-X9WRT-4HNBV-28FLC', { delay: 10 });
await shot('act_key', { input: p.locator('input').first(), submit: btn('เปิดใช้งาน') }, 100);
await btn('เปิดใช้งาน').click(); await shot('act_wait', {}, 300);
await shot('act_done', { settings: btn('ตั้งค่า'), grid: p.locator('main').first() }, 1700);
await btn('ตั้งค่า').click();
await shot('set_general', { install: btn('ติดตั้ง'), tools: p.getByText('เครื่องมือบนเครื่องนี้').first() }, 700);
await btn('ติดตั้ง').click(); await seq('set_pack', 6, 320);
await shot('set_pack_done', { pack: p.getByText('ตัวเรนเดอร์กราฟิก').first() }, 1200);
await tab('ถอดเสียง').click();
await shot('set_asr', { local: p.getByText('บนเครื่อง · Whisper large-v3').first(), dl: btn('ดาวน์โหลดโมเดล'), eleven: p.getByText('ElevenLabs Scribe').first() }, 600);
await btn('ดาวน์โหลดโมเดล').click(); await seq('set_model', 8, 330);
await shot('set_model_done', { ready: p.getByText(/โมเดลพร้อมใช้งาน/).first() }, 1200);
await tab('Claude').click();
await shot('set_claude', { api: p.getByText('Anthropic API', { exact: true }).first(), key: p.getByLabel('Anthropic API key'), save: btn('บันทึก key'), cc: p.getByText('Claude Code บนเครื่องนี้').first() }, 600);
await p.getByLabel('Anthropic API key').pressSequentially('sk-ant-api03-xxxxxxxxxxxxa1B2', { delay: 5 });
await shot('set_claude_key', { key: p.getByLabel('Anthropic API key'), save: btn('บันทึก key') }, 100);
await btn('บันทึก key').click(); await shot('set_claude_saved', {}, 600);
await p.getByText('Claude Code บนเครื่องนี้').first().click();
await shot('set_cc', { install: btn(/ติดตั้ง Claude Code/), cc: p.getByText('Claude Code บนเครื่องนี้').first() }, 700);
await btn(/ติดตั้ง Claude Code/).click(); await shot('set_cc_installing', {}, 600);
await shot('set_cc_installed', { login: btn(/ล็อกอิน/) }, 1600);
await btn(/ล็อกอิน/).click(); await shot('set_cc_login', {}, 500);
await shot('set_cc_ready', { cc: p.getByText('Claude Code บนเครื่องนี้').first() }, 1700);
await tab('License').click(); await shot('set_license', { card: p.locator('main').first() }, 600);

/* ---- CapCut must be closed ---- */
await open('?capcut');
await shot('gate', { bar: p.getByText(/CapCut เปิดอยู่/).first() }, 300);
await p.evaluate(() => (window.__demo.capcut.running = false));
await shot('gate_off', {}, 3500);

/* ---- the work ---- */
await open('');
await shot('projects', { card: p.getByText('รีวิวเซรั่ม 0930').first().locator('xpath=ancestor::*[self::button or self::a or self::li][1]'), search: p.getByPlaceholder('ค้นหาโปรเจค') });
await p.getByText('รีวิวเซรั่ม 0930').first().click();
await shot('prepare', { list: p.locator('.card, ul').first(), check: p.locator('input[type=checkbox]').first(), estimate: p.getByText(/Claude จะดูภาพประมาณ/).first(), start: btn('เริ่มวิเคราะห์') }, 900);
await btn('เริ่มวิเคราะห์').click(); await seq('analyse', 20, 380);
await shot('analysed', { peek: btn('ดู'), next: btn('ไปโครงเรื่อง') }, 1500);
await btn('ดู').first().click(); await shot('peek', { pop: p.locator('[role=dialog], .popover, .sheet').first() }, 700);
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await btn('ไปโครงเรื่อง').click();
await shot('brief', { card: p.getByText('โจทย์ของคลิป').first(), len: p.getByText('30 วินาที', { exact: true }), type: p.locator('select').first(), text: p.locator('textarea').first(), submit: btn('ให้ AI วางโครงเรื่อง') }, 1000);
await p.getByText('30 วินาที', { exact: true }).click(); await p.locator('select').first().selectOption('sales');
await p.locator('textarea').first().fill('เปิดด้วยช็อตสินค้า เน้นโปรโมชั่นตอนท้าย');
await shot('brief_filled', { len: p.getByText('30 วินาที', { exact: true }), type: p.locator('select').first(), text: p.locator('textarea').first(), submit: btn('ให้ AI วางโครงเรื่อง') }, 200);
await btn('ให้ AI วางโครงเรื่อง').click(); await shot('planning', {}, 900);
await shot('outline', { head: p.getByText('รีวิวเซรั่มผิวฉ่ำ').first(), beat1: p.getByText('เปิดด้วยสินค้า').first(), play: btn(/ดูตัวอย่าง/).nth(1), up: btn('เลื่อนขึ้น').nth(1), remove: btn('ลบช่วงนี้').nth(1), revise: p.getByPlaceholder(/ตัดช่วงแนะนำตัวออก/), confirm: btn('ยืนยันโครงเรื่อง') }, 2400);
await p.getByPlaceholder(/ตัดช่วงแนะนำตัวออก/).fill('ตัดช่วงผลลัพธ์ให้สั้นลง ให้เหลือไม่เกิน 30 วินาที');
await shot('outline_revise', { revise: p.getByPlaceholder(/ตัดช่วงแนะนำตัวออก/), send: btn('ส่งให้ AI แก้') }, 200);
await p.getByPlaceholder(/ตัดช่วงแนะนำตัวออก/).fill('');
await btn('ยืนยันโครงเรื่อง').click();
await shot('post', { beats: p.locator('aside, nav').first(), tabs: p.getByRole('tablist').first() }, 1800);
await p.getByRole('button', { name: /ปัญหาผิวแห้ง/ }).first().click();
await shot('post_cut', { rows: p.locator('.speech-row').first(), pills: p.locator('.speech-row .pill').nth(1), rules: p.getByText('กติกาการตัด').first(), plan: btn(/วางแผน post-production/) }, 800);
await btn(/วางแผน post-production/).click(); await seq('post_plan', 14, 380);
await shot('post_planned', { menu: btn(/ให้ AI คิด/), write: btn('เขียนลง CapCut') }, 1200);
await p.getByRole('button', { name: /โปรโมชั่น/ }).first().click();
await tab(/จุดเน้น/).click(); await shot('tab_emph', { point: p.locator('.emphasis-point').first(), level: p.getByText('ระดับความจัด').first() }, 800);
await tab(/กราฟิกและเทคนิค/).click(); await shot('tab_gfx', { group: p.locator('li.highlight-group').first(), graphic: p.locator('li.flair-row.graphic').first(), switches: p.locator('.graphics-tab').first() }, 900);
await tab(/เสียง/).click(); await shot('tab_sound', { row: p.locator('li.flair-row').first() }, 800);
await p.getByRole('button', { name: /ปัญหาผิวแห้ง/ }).first().click();
await tab(/ซับ/).click(); await shot('tab_subs', { first: p.locator('input[type=text], textarea').first() }, 800);
await btn(/ให้ AI คิด/).click(); await shot('ai_menu', { menu: p.getByText('คิดใหม่: จุดเน้น').first() }, 500);
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await btn('เขียนลง CapCut').click(); await shot('write_pop', { pop: p.getByText(/เขียนลง “รีวิวเซรั่ม 0930”/).first(), go: btn('เขียนเลย') }, 600);
await btn('เขียนเลย').click(); await shot('writing', {}, 400);
await shot('written', { bar: btn(/สำรอง/) }, 1900);
await btn(/สำรอง/).click(); await shot('backups', { pop: p.getByText(/กู้คืน/).first() }, 700);
writeFileSync(process.argv[2] + '/shots/manifest.json', JSON.stringify(man, null, 1));
await b.close();
