import type { Segment, TimeRange, Track } from "./types.ts"

/**
 * Caption shapes copied from what CapCut Mac 9.4.0 wrote after importing an .srt
 * (Text → Local captions) and turning on a black stroke for all captions
 * (draft 0917, 2026-09-17). `type: "subtitle"` materials sharing one `group_id`
 * are one caption group: CapCut restyles them together.
 */

const FONT_PATH = "/Applications/CapCut.app/Contents/Resources/Font/SystemFont/en.ttf"
const STROKE_WIDTH = 0.08

export function captionTrack(id: string, segments: Segment[]): Track {
  return { id, type: "text", flag: 1, attribute: 0, name: "", is_default_name: true, segments }
}

/** `range` counts UTF-16 code units, which is what String.length measures. */
function textContent(text: string) {
  return {
    styles: [
      {
        fill: { content: { solid: { color: [1, 1, 1] }, render_type: "solid" } },
        range: [0, text.length],
        strokes: [{ width: STROKE_WIDTH, mode: 0, content: { solid: { color: [0, 0, 0] }, render_type: "solid" } }],
        size: 11,
        font: { path: FONT_PATH, id: "" },
      },
    ],
    text,
  }
}

export function captionMaterial(args: { id: string; text: string; groupId: string }): { id: string; [key: string]: unknown } {
  return {
    recognize_task_id: "",
    id: args.id,
    name: "",
    recognize_text: "",
    recognize_model: "",
    punc_model: "",
    type: "subtitle",
    content: JSON.stringify(textContent(args.text)),
    base_content: "",
    words: {"start_time":[],"end_time":[],"text":[]},
    current_words: {"start_time":[],"end_time":[],"text":[]},
    global_alpha: 1,
    combo_info: {"text_templates":[]},
    caption_template_info: {"resource_id":"","third_resource_id":"","resource_name":"","category_id":"","category_name":"","effect_id":"","request_id":"","path":"","is_new":false,"source_platform":0},
    layer_weight: 1,
    letter_spacing: 0,
    text_curve: null,
    text_loop_on_path: false,
    offset_on_path: 0,
    enable_path_typesetting: false,
    text_exceeds_path_process_type: 0,
    text_typesetting_paths: null,
    text_typesetting_paths_file: "",
    text_typesetting_path_index: 0,
    line_spacing: 0.02,
    has_shadow: false,
    shadow_color: "",
    shadow_alpha: 0.9,
    shadow_smoothing: 0.45,
    shadow_distance: 5,
    shadow_point: {"x":0.6363961030678928,"y":-0.6363961030678927},
    shadow_angle: -45,
    shadow_thickness_projection_enable: false,
    shadow_thickness_projection_angle: 0,
    shadow_thickness_projection_distance: 0,
    border_alpha: 1,
    border_color: "#000000",
    border_width: STROKE_WIDTH,
    border_mode: 0,
    style_name: "",
    text_color: "#FFFFFF",
    text_alpha: 1,
    font_name: "",
    font_title: "none",
    font_size: 11,
    font_path: FONT_PATH,
    font_id: "",
    font_resource_id: "",
    initial_scale: 1,
    font_url: "",
    typesetting: 0,
    alignment: 1,
    line_feed: 1,
    use_effect_default_color: true,
    is_rich_text: false,
    shape_clip_x: false,
    shape_clip_y: false,
    ktv_color: "",
    text_to_audio_ids: [],
    bold_width: 0,
    italic_degree: 0,
    underline: false,
    underline_width: 0.05,
    underline_offset: 0.22,
    sub_type: 0,
    check_flag: 15,
    text_size: 30,
    font_category_name: "",
    font_source_platform: 0,
    font_third_resource_id: "",
    font_category_id: "",
    add_type: 2,
    operation_type: 0,
    recognize_type: 0,
    fonts: [],
    background_color: "",
    background_alpha: 1,
    background_style: 0,
    background_round_radius: 0,
    background_width: 0.14,
    background_height: 0.14,
    background_vertical_offset: 0,
    background_horizontal_offset: 0,
    background_fill: "",
    single_char_bg_enable: false,
    single_char_bg_color: "",
    single_char_bg_alpha: 1,
    single_char_bg_round_radius: 0.3,
    single_char_bg_width: 0,
    single_char_bg_height: 0,
    single_char_bg_vertical_offset: 0,
    single_char_bg_horizontal_offset: 0,
    font_team_id: "",
    tts_auto_update: false,
    text_preset_resource_id: "",
    group_id: args.groupId,
    preset_id: "",
    preset_name: "",
    preset_category: "",
    preset_category_id: "",
    preset_index: 0,
    preset_has_set_alignment: false,
    force_apply_line_max_width: false,
    language: "",
    relevance_segment: [],
    original_size: [],
    fixed_width: -1,
    fixed_height: -1,
    autoAdaptCanvasEnabled: false,
    line_max_width: 0.82,
    oneline_cutoff: false,
    cutoff_postfix: "",
    subtitle_template_original_fontsize: 0,
    subtitle_keywords: null,
    inner_padding: -1,
    multi_language_current: "none",
    source_from: "",
    is_lyric_effect: false,
    lyric_group_id: "",
    lyrics_template: {"resource_id":"","resource_name":"","panel":"","effect_id":"","path":"","category_id":"","category_name":"","request_id":""},
    is_batch_replace: false,
    is_words_linear: false,
    ssml_content: "",
    subtitle_keywords_config: null,
    sub_template_id: -1,
    translate_original_text: "",
  }
}

export function captionAnimation(id: string): { id: string; [key: string]: unknown } {
  return { id, type: "sticker_animation", animations: [], multi_language_current: "none" }
}

export function captionSegment(args: { id: string; materialId: string; animationId: string; target: TimeRange }): Segment {
  return {
    id: args.id,
    source_timerange: null,
    target_timerange: args.target,
    render_timerange: {"start":0,"duration":0},
    desc: "",
    state: 0,
    speed: 1,
    is_loop: false,
    is_tone_modify: false,
    reverse: false,
    intensifies_audio: false,
    cartoon: false,
    volume: 1,
    last_nonzero_volume: 1,
    clip: {"scale":{"x":1,"y":1},"rotation":0,"transform":{"x":0,"y":-0.8},"flip":{"vertical":false,"horizontal":false},"alpha":1},
    uniform_scale: {"on":true,"value":1},
    material_id: args.materialId,
    extra_material_refs: [args.animationId],
    render_index: 14000,
    keyframe_refs: [],
    enable_lut: false,
    enable_adjust: false,
    enable_hsl: false,
    visible: true,
    group_id: "",
    enable_color_curves: true,
    enable_hsl_curves: true,
    track_render_index: 1,
    hdr_settings: null,
    hdr_vivid_settings: null,
    enable_color_wheels: true,
    track_attribute: 0,
    is_placeholder: false,
    template_id: "",
    enable_smart_color_adjust: false,
    template_scene: "default",
    common_keyframes: [],
    caption_info: null,
    responsive_layout: {"enable":false,"target_follow":"","size_layout":0,"horizontal_pos_layout":0,"vertical_pos_layout":0},
    enable_color_match_adjust: false,
    enable_color_correct_adjust: false,
    enable_adjust_mask: false,
    raw_segment_id: "",
    lyric_keyframes: null,
    enable_video_mask: true,
    digital_human_template_group_id: "",
    color_correct_alg_result: "",
    source: "segmentsourcenormal",
    enable_mask_stroke: false,
    enable_mask_shadow: false,
    enable_color_adjust_pro: false,
    segment_color_tag: "",
  }
}
